BEGIN TRANSACTION;
INSERT INTO CATALOG (ID, MODVERSION, SOURCEORGANIZATIONID, CTSOURCEORGANIZATIONID, CATALOGTYPEID, NAME, DESCRIPTION, ACTIVE, MODMEMBERID, MODDATE, SYSTEMGENERATED, PRODUCTCOUNT, LOGFILE, TYPE, TABLENAME,DISPLAYNAME) VALUES (6, 1, 1, 1, 6, 'TIBCO', 'TIBCO predefined output map', 'Y', 101, '2007-10-19 18:06:00', 'Y', 0, NULL, 'OUTPUTCATALOG', NULL, 'TIBCO');
COMMIT;
