BEGIN TRANSACTION;
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (1, 'adminmenu', 'admin menu', 'adminmenu');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (2, 'adminmenu_member', 'User administration menu', 'adminmenu_member');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (3, 'adminmenu_enterprise', 'Enterprise profiles management menu', 'adminmenu_enterprise');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (4, 'adminmenu_company', 'Company profile management menu', 'adminmenu_company');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (5, 'adminmenu_market', 'Datapool/integration hub profile management menu', 'adminmenu_market');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (6, 'adminmenu_buyers', 'Partner profile management menu', 'adminmenu_buyers');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (7, 'catalogmenu', 'Master data main menu', 'catalogmenu');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (8, 'catalogmenu_master_catalog', 'Repositories management menu', 'catalogmenu_master_catalog');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (9, 'catalogmenu_data_source', 'Data source management menu', 'catalogmenu_data_source');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (13, 'catalogmenu_catalog_edition', 'Synchronization profile main menu', 'catalogmenu_catalog_edition');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (14, 'catalogmenu_catalog_adapter', 'Synchronization format management menu', 'catalogmenu_catalog_adapter');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (15, 'catalogmenu_catalog_search', 'Record search menu', 'catalogmenu_catalog_search');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (16, 'catalogmenu_mass_update', 'Mass Update menu item', 'catalogmenu_mass_update');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (21, 'adminmenu_event_log', 'Event log menu', 'taskmenu_event_log');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (24, 'my_info', 'My account management', 'my_info');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (27, 'busprocmenu', 'Business process management menu', 'busprocmenu');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (48, 'adminmenu_permissions', 'Resource security management menu', 'adminmenu_permissions');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (61, 'adminmenu_roles', 'Roles menu', 'adminmenu_roles');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (66, 'exportmenu', 'System administration - meta data export menu ', 'exportmenu');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (67, 'importmenu', 'System administration - meta data import menu ', 'importmenu');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (68, 'sysopmenu', 'System administration main menu', 'sysopmenu');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (69, 'queryopmenu', 'Allowing  query operations', 'query');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (70, 'allow_view_entitlement', 'Allows to view entitlement for user', 'allow_view_entitlement');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (72, 'inbox', 'inbox', 'inbox');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (71, 'catalogmenu_subset_rules', 'Subset rules', 'catalogmenu_subset_rules');
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (73, 'allow_jmx_administration', 'JMX Rest access', 'allow_jmx_administration') ;
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (74, 'allow_CLI', 'allow command line access', 'allow_CLI') ;
INSERT INTO FUNCTION (ID, NAME, DESCRIPTION, FUNCTION) VALUES (75, 'datatransfermenu', 'System Administration - Data Transfer Menu', 'datatransfermenu') ;

COMMIT;
