BEGIN TRANSACTION;
INSERT INTO ROLEASSIGNMENT (ROLEID, MEMBERID, MODDATE, MEMBERVERSION, MODMEMBERID) VALUES (50, 101, NULL, NULL, NULL);
INSERT INTO ROLEASSIGNMENT (ROLEID, MEMBERID, MODDATE, MEMBERVERSION, MODMEMBERID) VALUES (51, 101, NULL, NULL, NULL);
COMMIT;
