/* Data for the `SCREEN` table  (Records 2001-...) */
DO LANGUAGE plpgsql $$ 
DECLARE
 SCREEN_ID smallint;
BEGIN
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '2001';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('2001', 'EN', 'FP Catalog Synchronization', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1102';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1102', 'EN', 'Publish Catalog', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1103';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1103', 'EN', 'Publish Catalog Status', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1104';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1104', 'EN', 'Export FC Data Status', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1105';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1105', 'EN', 'Import FC Data', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1106';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1106', 'EN', 'Import FC Data Status', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1107';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1107', 'EN', 'Export FC Data', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1111';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1111', 'EN', 'Hierarchy Management', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1113';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1113', 'EN', 'Delta Import', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1114';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1114', 'EN', 'Bulk Delete', NULL);
	END IF;
	
	SELECT COUNT(1) INTO SCREEN_ID FROM SCREEN WHERE SCREENID = '1115';
	IF SCREEN_ID = 0 THEN 
		INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) VALUES ('1115', 'EN', 'Bulk Delete Status', NULL);
	END IF;	
END;
$$;