-- Copyright (c) 2000-2009 TIBCO Software Inc. All Rights Reserved.

--  This work is subject  to  U.S. and  international  copyright  laws  and
--     treaties. No part  of  this  work may be  used,  practiced,  performed
--     copied, distributed, revised, modified, translated,  abridged, condensed,
--     expanded,  collected,  compiled,  linked,  recast, transformed or adapted
--     without the prior written consent of TIBCO Software Inc. any use or
--     exploitation of this work without authorization could subject the
--     perpetrator to criminal and civil liability.
--
-- Note   : Please DO NOT edit the script.

--
-- DEFINITION FOR VIEW CATALOGINPUTFORMAT:
--

CREATE OR REPLACE VIEW CATALOGINPUTFORMAT
(
  ID,
  NAME,
  DESCRIPTION,
  ACTIVE,
  MODMEMBERID,
  MODDATE,
  MODVERSION
)
AS
 SELECT ID,NAME,DESCRIPTION,ACTIVE,MODMEMBERID,MODDATE,MODVERSION FROM CATALOGFORMAT;

--
-- DEFINITION FOR VIEW CATALOGOUTPUTFORMAT:
--

CREATE OR REPLACE VIEW CATALOGOUTPUTFORMAT
(
  ID,
  SOURCEORGANIZATIONID,
  NAME,
  DESCRIPTION,
  FIXEDLENGTH,
  HEADERREQUIRED,
  DELIMITER,
  ACTIVE,
  MODMEMBERID,
  MODDATE,
  MODVERSION
)
AS
  SELECT ID,SOURCEORGANIZATIONID,NAME,DESCRIPTION,FIXEDLENGTH,HEADERREQUIRED,DELIMITER,ACTIVE,MODMEMBERID,MODDATE,MODVERSION FROM CATALOGTYPE;

--
-- DEFINITION FOR VIEW CATALOGOUTPUTFORMATATTRIBUTE:
--

CREATE OR REPLACE VIEW CATALOGOUTPUTFORMATATTRIBUTE
(
  ID,
  SOURCEORGANIZATIONID,
  CATALOGTYPEID,
  NAME,
  DESCRIPTION,
  CATALOGATTRIBUTEDATATYPEID,
  ATTRIBUTELENGTH,
  ATTRIBUTEPOSITION,
  REQUIRED,
  ACTIVE
)
AS
  SELECT ID,SOURCEORGANIZATIONID,CATALOGTYPEID,NAME,DESCRIPTION,CATALOGATTRIBUTEDATATYPEID,ATTRIBUTELENGTH,ATTRIBUTEPOSITION,REQUIRED,ACTIVE FROM CATALOGTYPEATTRIBUTE;

--
-- DEFINITION FOR VIEW CLASSIFICATIONSCHEMEATTRIBUTE:
--

CREATE OR REPLACE VIEW CLASSIFICATIONSCHEMEATTRIBUTE
(
  SOURCEORGANIZATIONID,
  CATALOGID,
  CLASSIFICATIONSCHEMEID,
  HIERARCHYPOSITION,
  SOURCEEXPRESSION,
  ACTIVE,
  MODMEMBERID,
  MODDATE,
  MODVERSION,
  CSVERSIONNUMBER
)
AS
  SELECT SOURCEORGANIZATIONID,CATALOGID,CLASSIFICATIONSCHEMEID,HIERARCHYPOSITION,SOURCEEXPRESSION, ACTIVE,MODMEMBERID,MODDATE,MODVERSION,CSVERSIONNUMBER FROM CLASSIFICATIONATTRIBUTE;

--
-- DEFINITION FOR VIEW DATASOURCE:
--

CREATE OR REPLACE VIEW DATASOURCE
(
  ID,
  SOURCEORGANIZATIONID,
  CATALOGFORMATID,
  NAME,
  DESCRIPTION,
  FILENAME,
  DELIMITER,
  HEADERLINECOUNT,
  USETITLESFLAG,
  FILELASTUPLOADEDDATE,
  TABLELASTUPLOADEDDATE,
  SOURCETABLENAME,
  LOADEDROWCOUNT,
  BADROWCOUNT,
  LOGFILE,
  BADFILE,
  TRANSPORTPROTOCOL,
  TRANSPORTPROTOCOLADDRESSID,
  ACTIVE,
  MODMEMBERID,
  MODDATE,
  MODVERSION,
  PRICELISTFLAG,
  UPLOADMETHOD,
  INTERNALFILENAME,
  DATEFORMAT
)
AS
  SELECT ID,SOURCEORGANIZATIONID,CATALOGFORMATID,NAME,DESCRIPTION,FILENAME,DELIMITER,HEADERLINECOUNT,USETITLESFLAG,FILELASTUPLOADEDDATE,
  TABLELASTUPLOADEDDATE, SOURCETABLENAME,LOADEDROWCOUNT,BADROWCOUNT,LOGFILE,BADFILE,TRANSPORTPROTOCOL, TRANSPORTPROTOCOLADDRESSID,ACTIVE,
  MODMEMBERID,MODDATE,MODVERSION,PRICELISTFLAG,UPLOADMETHOD,INTERNALFILENAME, DATEFORMAT 
  FROM
  DATAFRAGMENT;

--
-- DEFINITION FOR VIEW DATASOURCEATTRIBUTE:
--

CREATE OR REPLACE VIEW DATASOURCEATTRIBUTE
(
  ID,
  SOURCEORGANIZATIONID,
  DATAFRAGMENTID,
  CATALOGATTRIBUTEDATATYPEID,
  NAME,
  DESCRIPTION,
  ATTRIBUTEPOSITION,
  ATTRIBUTELENGTH,
  REQUIRED,
  ACTIVE,
  MODMEMBERID,
  MODDATE,
  MODVERSION
)
AS
  SELECT ID,SOURCEORGANIZATIONID,DATAFRAGMENTID,CATALOGATTRIBUTEDATATYPEID,NAME,DESCRIPTION,ATTRIBUTEPOSITION, ATTRIBUTELENGTH,REQUIRED,
  ACTIVE,MODMEMBERID,MODDATE,MODVERSION
  FROM
  DFATTRIBUTE;

--
-- DEFINITION FOR VIEW PROTOCOLVIEWFTP:
--

CREATE OR REPLACE VIEW PROTOCOLVIEWFTP
(
  ID,
  OWNERID,
  NAME,
  VALUE
)
AS
  SELECT ID, OWNERID, ('FTP ' || NAME || ' (' || LOGINNAME || '@' || HOST || ' ' || DIRECTORY  || ')'),
  (LOGINNAME || '&' || PASSWORD || '&' || HOST || '&' || DIRECTORY) FROM FTP WHERE FTP.ACTIVE = 'Y' ;

--
-- DEFINITION FOR VIEW PROTOCOLVIEWHTTP:
--

CREATE OR REPLACE VIEW PROTOCOLVIEWHTTP
(
  ID,
  OWNERID,
  NAME,
  VALUE
)
AS
SELECT ID, OWNERID, ('URL ' || NAME || ' (' || SUBSTR(URL,1,80) || ')') , URL FROM HTTP WHERE HTTP.ACTIVE = 'Y' ;

--
-- DEFINITION FOR VIEW PROTOCOLVIEWSMTP:
--

CREATE OR REPLACE VIEW PROTOCOLVIEWSMTP
(
  ID,
  OWNERID,
  NAME,
  VALUE
)
AS
  SELECT ID, OWNERID, ('EMAIL ' || NAME || ' (' || EMAIL || ')'), EMAIL FROM EMAIL WHERE ACTIVE ='Y';


--
-- DEFINITION FOR VIEW VRELATIONSHIPLIST:
--

CREATE OR REPLACE VIEW VRELATIONSHIPLIST
(
  NAME,
  OWNERID,
  TYPE,
  DIRECTION
)
AS
  SELECT REL.NAME, REL.OWNERID, REL.TYPE, REL.DIRECTION
  FROM 
  (SELECT DISTINCT NAME, TYPE, 0 DIRECTION, OWNERID 
  	FROM RELATIONSHIPDEFINITION RD WHERE ACTIVE='Y' AND RD.MODVERSION = (SELECT MAX (MODVERSION) FROM RELATIONSHIPDEFINITION RD1  WHERE RD.OWNERID = RD1.OWNERID AND RD.NAME=RD1.NAME)
  	UNION 
  	SELECT DISTINCT (REVERSENAME) AS NAME, TYPE, 1 DIRECTION, 
  		CASE TARGETCATALOGID 
  		WHEN -1
  		THEN OWNERID
  		ELSE TARGETCATALOGID
  		END  OWNERID FROM RELATIONSHIPDEFINITION RD
  	WHERE   ACTIVE='Y' 
  	AND RD.MODVERSION = (SELECT MAX (MODVERSION) FROM RELATIONSHIPDEFINITION RD1  WHERE RD.TARGETCATALOGID=RD1.TARGETCATALOGID AND RD.REVERSENAME=RD1.REVERSENAME)
  ) AS REL;


--
-- DEFINITION FOR VIEW VROLEASSIGHISTORY:
--

CREATE OR REPLACE VIEW VROLEASSIGHISTORY (ROLE_NAME, MEMBER_NAME, WHO_DID_IT)
AS
  SELECT (SELECT R.NAME FROM ROLE R WHERE R.ID = ROLEASSIGHISTORY.ROLEID) ROLE_NAME,
    (SELECT M.USERNAME FROM MEMBER M WHERE M.ID = ROLEASSIGHISTORY.MEMBERID) MEMBER_NAME,
    (SELECT M.USERNAME FROM MEMBER M WHERE M.ID = ROLEASSIGHISTORY.MODMEMBERID) WHO_DID_IT
  FROM 
  ROLEASSIGHISTORY ;

--
-- DEFINITION FOR VIEW V_REPOSITORY:
--
  
CREATE OR REPLACE VIEW V_REPOSITORY (ID, NAME, description, sourceorganizationid, moddate, modmemberid, modversion, type)
AS
  SELECT ID,
    NAME,
    description,
    sourceorganizationid,
    moddate,
    modmemberid,
    modversion,
    type
  FROM catalog c
  WHERE 
  active   ='Y'
  AND precedencemanagement = 'Y'
  AND type IN ('CATALOG','RELATIONSHIPCATALOG')
  AND modversion = (SELECT MAX(modversion) FROM catalog s WHERE s.id = c.id GROUP BY id);
    
    
--
-- DEFINITION FOR VIEW V_REPOSITORYATTRIBUTE:
--

CREATE OR REPLACE VIEW V_REPOSITORYATTRIBUTE (ID, name, description,displayname, catalogid)
AS
SELECT ca.ID,
    ca.name,
    ca.description,
    ca.displayname,
    ca.catalogid
  FROM catalogattribute ca, V_REPOSITORY vr
  WHERE 
  active ='Y'
  AND ca.catalogid = vr.id
  AND ca.catalogversionnumber = vr.modversion;		  


--
-- DEFINITION FOR VIEW V_MDMFUNCTION:
--
  
CREATE OR REPLACE VIEW V_MDMFUNCTION (ID,FUNCTIONID, NAME, DESCRIPTION)
AS
  SELECT ID, FUNCTION, NAME, DESCRIPTION FROM FUNCTION;