-- Copyright (c) 2000-2009 TIBCO Software Inc. All Rights Reserved.

--  This work is subject  to  U.S. and  international  copyright  laws  and
--     treaties. No part  of  this  work may be  used,  practiced,  performed
--     copied, distributed, revised, modified, translated,  abridged, condensed,
--     expanded,  collected,  compiled,  linked,  recast, transformed or adapted
--     without the prior written consent of TIBCO Software Inc. any use or
--     exploitation of this work without authorization could subject the
--     perpetrator to criminal and civil liability.
--
-- Note   : Please DO NOT edit the script.

BEGIN TRANSACTION;

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('001', 'EN', 'Document Viewer', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('002', 'EN', 'Event Details', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('003', 'EN', 'Events', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('004', 'EN', 'Synchronized Record List', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('005', 'EN', 'Classificaion Code Attributes', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('006', 'EN', 'Synchronized Record View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('007', 'EN', 'Import Mappings', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('008', 'EN', 'Import Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('009', 'EN', 'Catalog', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('010', 'EN', 'Catalog Synchronization Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('018', 'EN', 'Catalog Validation Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('011', 'EN', 'Catalog View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('012', 'EN', 'Catalog Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('013', 'EN', 'Catalog Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('014', 'EN', 'Catalog Synchronization', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('015', 'EN', 'Catalog Validation', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('017', 'EN', 'Product Details', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('020', 'EN', 'Data Sources for Import', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('021', 'EN', 'Master Catalogs', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('022', 'EN', 'Master Catalog View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('023', 'EN', 'Master Catalog Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('024', 'EN', 'Master Catalog Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('030', 'EN', 'Output Map View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('031', 'EN', 'Output Map Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('032', 'EN', 'Output Map Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('033', 'EN', 'Output Map Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('040', 'EN', 'Transformation Rules', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('041', 'EN', 'Transformation Rule View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('042', 'EN', 'Transformation Rule Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('043', 'EN', 'Transformation Rule Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('050', 'EN', 'Catalog Formats', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('051', 'EN', 'Catalog Format View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('052', 'EN', 'Catalog Format Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('053', 'EN', 'Catalog Format Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('060', 'EN', 'Search Record for Containment', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('061', 'EN', 'Record Containment View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('062', 'EN', 'Record Save Validation', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('063', 'EN', 'File Upload', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('070', 'EN', 'Data Sources', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('071', 'EN', 'Data Source View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('072', 'EN', 'Data Source Modify', 'Catalog - Data Sources - Modify Data Source.htm');

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('073', 'EN', 'Data Source Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('075', 'EN', 'Upload Data Source', 'Catalog - Data Sources - Upload Data Source.htm');

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('076', 'EN', 'Data Source Upload Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('080', 'EN', 'Price Lists', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('081', 'EN', 'Price List View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('082', 'EN', 'Price List Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('083', 'EN', 'Price List Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('084', 'EN', 'Upload Price List', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('085', 'EN', 'Price List Upload Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('090', 'EN', 'Record History', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('091', 'EN', 'Record History - Event Details', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('092', 'EN', 'Record Search', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('093', 'EN', 'Records', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('094', 'EN', 'Synchronized Record Search', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('095', 'EN', 'Record View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('096', 'EN', 'Record Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('097', 'EN', 'Record Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('098', 'EN', 'Record Compare', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('099', 'EN', 'Record Add', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('100', 'EN', 'Subset Rules', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('101', 'EN', 'Subset Rule View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('102', 'EN', 'Subset Rule Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('103', 'EN', 'Subset Rule Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('104', 'EN', 'Records Selected by Subset Rule', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('105', 'EN', 'Search Records for Inclusion in Subset', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('106', 'EN', 'Record Rejection', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('110', 'EN', 'Create Named Version', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('120', 'EN', 'Browse Master Catalog', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('121', 'EN', 'Browse Catalog', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('150', 'EN', 'Master Catalog Wizard Completion', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('151', 'EN', 'Catalog History', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('152', 'EN', 'Catalog History - Event Details', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('153', 'EN', 'Data Source Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('154', 'EN', 'Price List Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('155', 'EN', 'Master Catalog Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('156', 'EN', 'Catalog Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('157', 'EN', 'Transformation Rule Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('158', 'EN', 'Subset Rule Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('159', 'EN', 'Catalog Format Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('160', 'EN', 'Classifiction Scheme Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('161', 'EN', 'Output Map Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('170', 'EN', 'Classification Scheme Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('171', 'EN', 'Classificatation Scheme View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('172', 'EN', 'Classification Scheme Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('180', 'EN', 'Classification Scheme Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('181', 'EN', 'Master Catalog Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('182', 'EN', 'Catalog Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('183', 'EN', 'Output Map Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('184', 'EN', 'Record Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('185', 'EN', 'Subset Rule Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('186', 'EN', 'Transformation Rule Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('187', 'EN', 'Data Source Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('188', 'EN', 'Price List Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('189', 'EN', 'Catalog Format Usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('200', 'EN', 'Company View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('201', 'EN', 'Company Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('202', 'EN', 'Company Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('205', 'EN', 'Enterprise View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('206', 'EN', 'Enterprise Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('207', 'EN', 'Enterprises', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('208', 'EN', 'Enterprise Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('209', 'EN', 'Organization Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('210', 'EN', 'Trading Partner View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('211', 'EN', 'Trading Partner Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('212', 'EN', 'Trading Partner Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('213', 'EN', 'Trading Partner Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('214', 'EN', 'Trading Partners', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('215', 'EN', 'Trading Partners', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('216', 'EN', 'Trading Partner View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('217', 'EN', 'Trading Partner Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('218', 'EN', 'Trading Partner Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('219', 'EN', 'Trading Partner Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('220', 'EN', 'Emails', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('221', 'EN', 'Email Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('222', 'EN', 'Email Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('225', 'EN', 'FTP Addresses', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('226', 'EN', 'FTP Address Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('227', 'EN', 'FTP Address Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('230', 'EN', 'HTML Addresses', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('231', 'EN', 'HTML Address Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('232', 'EN', 'HTML Address Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('235', 'EN', 'Phone Numbers', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('236', 'EN', 'Phone Number Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('237', 'EN', 'Phone Number Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('240', 'EN', 'Postal Addresses', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('241', 'EN', 'Postal Address Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('242', 'EN', 'Postal Address Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('243', 'EN', 'FTP Address View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('244', 'EN', 'EMAIL Address View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('245', 'EN', 'Phone Address View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('246', 'EN', 'HTML Address View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('250', 'EN', 'Channel', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('251', 'EN', 'Channel', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('252', 'EN', 'Channel', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('253', 'EN', 'Channel', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('254', 'EN', 'Channel - Supported Catalog Formats', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('260', 'EN', 'User Accounts', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('261', 'EN', 'User View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('262', 'EN', 'User Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('263', 'EN', 'User Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('264', 'EN', 'User Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('265', 'EN', 'Credential Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('266', 'EN', 'Credential Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('270', 'EN', 'My Account', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('271', 'EN', 'Credentials', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('280', 'EN', 'Reports', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('281', 'EN', 'Report Catagories', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('282', 'EN', 'Report Parameters', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('290', 'EN', 'Select Grantee', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('291', 'EN', 'Define Resource Security', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('300', 'EN', 'Workflows', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('301', 'EN', 'Workflow Upload', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('310', 'EN', 'Attachement Viewer', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('311', 'EN', 'Inbox', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('400', 'EN', 'Trading Partner Info Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('401', 'EN', 'Catalog Synchronization Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('403', 'EN', 'Order Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('404', 'EN', 'Order Delete Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('405', 'EN', 'Order Update Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('406', 'EN', 'Order Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('407', 'EN', 'Order Delete Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('408', 'EN', 'Record Add Appoval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('409', 'EN', 'New Record Edit Request', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('410', 'EN', 'Unknow Trading Partner Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('411', 'EN', 'Record Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('412', 'EN', 'Record Delete Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('413', 'EN', 'Record Edit Approval', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('414', 'EN', 'Record Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('415', 'EN', 'Record Publication Request', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('416', 'EN', 'Order Update Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('417', 'EN', 'Catalog Validate Notification', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('500', 'EN', 'Catalog Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('501', 'EN', 'Master Catalog Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('502', 'EN', 'Subset Rule Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('503', 'EN', 'Data Source Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('504', 'EN', 'Record Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('600', 'EN', 'Rule Templates', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('601', 'EN', 'Rule Domains', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('602', 'EN', 'Rules', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('603', 'EN', 'Rule Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('604', 'EN', 'Rule Template Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('605', 'EN', 'Rule Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('700', 'EN', 'Modify Attribute Group', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('701', 'EN', 'Create Attribute Group', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('702', 'EN', 'Attribute Groups', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('703', 'EN', 'Attribute Group Sequence', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('704', 'EN', 'Delete Attribute Group', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('800', 'EN', 'Error', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('810', 'EN', 'Monitoring and Administration', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('900', 'EN', 'Login', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('950', 'EN', 'Security Role List', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('130', 'EN', 'Send Response', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('019', 'EN', 'Associated Event Log', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('089', 'EN', 'Conflict resolution', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('418', 'EN', 'Conflict Resolution Request', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('951', 'EN', 'Update Synch Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('131', 'EN', 'Send Message', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('025', 'EN', 'Catalog Input Maps', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('026', 'EN', 'Create Input Map', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('027', 'EN', 'Modify Input Map', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('811', 'EN', 'Rulebase View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('812', 'EN', 'Rulebase Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('813', 'EN', 'Rule View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('814', 'EN', 'Rulebase Variable Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('815', 'EN', 'Rulebase Variable Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('816', 'EN', 'Rulebase Action Create', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('817', 'EN', 'Rulebase Action Modify', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('818', 'EN', 'Rule Sequence', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('819', 'EN', 'Rulebase Expression', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('955', 'EN', 'Request for CIN', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('820', 'EN', 'Upload Rulebase', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('132', 'EN', 'Meta-data Management - Import', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('133', 'EN', 'Meta-data Management - Import Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('134', 'EN', 'Meta-data Management - Export', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('135', 'EN', 'Meta-data Management - Export Status', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('830', 'EN', 'Mass Update', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('1000', 'EN', 'Mass Update Parameters', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('505', 'EN', 'Catalog Format Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('122', 'EN', 'Browse Imported Records', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('136', 'EN', 'Role Delegation Add', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('137', 'EN', 'Role Delegation View', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('028', 'EN', 'Copy Input Map', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('029', 'EN', 'Record Count', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('850', 'EN', 'Browse and Search', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('851', 'EN', 'Search Record For Relationship', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) 
VALUES ('255', 'EN', 'Datapool Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) 
VALUES ('267', 'EN', 'Credential Delete', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL) 
VALUES ('190', 'EN', 'Synchronization format usage', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('506', 'EN', 'Export Profile Copy', NULL);

INSERT INTO SCREEN(SCREENID, LANGUAGECODE, TITLE, HELPSCREENURL)
VALUES ('2011', 'EN', 'Data Transfer', NULL);

COMMIT;