-- Copyright (c) 2000-2009 TIBCO Software Inc. All Rights Reserved.

--  This work is subject  to  U.S. and  international  copyright  laws  and
--     treaties. No part  of  this  work may be  used,  practiced,  performed
--     copied, distributed, revised, modified, translated,  abridged, condensed,
--     expanded,  collected,  compiled,  linked,  recast, transformed or adapted
--     without the prior written consent of TIBCO Software Inc. any use or
--     exploitation of this work without authorization could subject the
--     perpetrator to criminal and civil liability.
--
-- Note   : Please DO NOT edit the script.

--BEGIN TRANSACTION;

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32487', '50', '61', 'SUPERUSER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32488', '52', '61', 'Catalog Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32489', '53', '61', 'Channel Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32490', '54', '61', 'Sales Rep', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32491', '56', '61', 'Buyer', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32492', '57', '61', 'Catalog Editor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32493', '58', '61', 'Catalog Approver', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32958', '50', '68', 'SUPERUSER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32959', '50', '67', 'SUPERUSER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32960', '50', '66', 'SUPERUSER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32961', '52', '68', 'Catalog Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32962', '52', '67', 'Catalog Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32963', '52', '66', 'Catalog Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32964', '53', '68', 'Channel Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32965', '53', '67', 'Channel Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32966', '53', '66', 'Channel Manager', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32967', '54', '68', 'Sales Rep', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32968', '54', '67', 'Sales Rep', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32969', '54', '66', 'Sales Rep', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32970', '55', '68', 'USER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32971', '55', '67', 'USER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32972', '55', '66', 'USER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32973', '56', '68', 'Buyer', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32974', '56', '67', 'Buyer', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32975', '56', '66', 'Buyer', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32976', '57', '68', 'Catalog Editor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32977', '57', '67', 'Catalog Editor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32978', '57', '66', 'Catalog Editor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32979', '58', '68', 'Catalog Approver', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32980', '58', '67', 'Catalog Approver', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('32981', '58', '66', 'Catalog Approver', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33018', '59', '68', 'Work Supervisor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33019', '59', '67', 'Work Supervisor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33020', '59', '66', 'Work Supervisor', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33021', '50', '4', 'SUPERUSER', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33022', '51', '4', 'Admin', '0');

INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33023', '51', '74', 'Admin', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33024', '52', '74', 'Catalog Manager', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33025', '53', '74', 'Channel Manager', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33026', '54', '74', 'Sales Rep', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33027', '55', '74', 'User', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33028', '56', '74', 'Buyer', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33029', '57', '74', 'Catalog Editor', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33030', '58', '74', 'Catalog Approver', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33031', '59', '74', 'Work supervisor', '0');
INSERT INTO ROLE2FUNCMAP(ID, ROLEID, FUNCID, NAME, PRIORITY)
VALUES ('33032', '60', '74', 'Support Engineer', '0');


--COMMIT;