-- Copyright (c) 2000-2009 TIBCO Software Inc. All Rights Reserved.

--  This work is subject  to  U.S. and  international  copyright  laws  and
--     treaties. No part  of  this  work may be  used,  practiced,  performed
--     copied, distributed, revised, modified, translated,  abridged, condensed,
--     expanded,  collected,  compiled,  linked,  recast, transformed or adapted
--     without the prior written consent of TIBCO Software Inc. any use or
--     exploitation of this work without authorization could subject the
--     perpetrator to criminal and civil liability.
--
-- Note   : Please DO NOT edit the script.

--BEGIN TRANSACTION;
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (1, 'DATE', 'DATE', 'DATE', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (2, 'INTEGER', 'INTEGER', 'INTEGER', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (3, 'NUMBER', 'DECIMAL', 'NUMBER', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (4, 'VARCHAR2', 'STRING', 'VARCHAR2', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (5, 'FILE', 'FILE', 'VARCHAR2', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (6, 'AMOUNT', 'AMOUNT', 'NUMBER', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (7, 'BOOLEAN', 'BOOLEAN', 'VARCHAR2', 'Y', 1, '2003-01-16 15:11:57', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (10, 'CUSTOM_DECIMAL', 'CUSTOM DECIMAL', 'NUMBER', 'Y', 1, '2007-03-29 12:27:14', 0);
INSERT INTO CATALOGATTRIBUTEDATATYPE (ID, NAME, DESCRIPTION, NATIVEDATATYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION) VALUES (13, 'TIMESTAMP', 'TIMESTAMP', 'TIMESTAMP', 'Y', 1, '2012-01-20 01:50:00', 0);
--COMMIT;
