--BEGIN TRANSACTION;
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (50, 0, 'SUPERUSER', 'super user', 'ACCESS', 'Y', 101, '2003-01-16 15:11:55', 1, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (51, 0, 'Admin', 'Admin', 'ACCESS', 'Y', 101, '2003-01-16 15:11:55', 1, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (52, 0, 'Catalog Manager', 'Catalog Administrator', 'ACCESS', 'Y', 101, '2003-01-16 15:11:55', 1, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (53, 0, 'Channel Manager', 'Channel Manager', 'ACCESS', 'Y', 101, '2003-01-16 15:11:55', 1, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (54, 0, 'Sales Rep', 'Sales Representative', 'ACCESS', 'Y', 101, '2003-01-16 15:11:55', 1, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (55, 0, 'USER', 'User', 'ACCESS', 'Y', 101, '2003-01-16 15:11:55', 1, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (56, 0, 'Buyer', 'External User', NULL, 'Y', 101, '2003-01-16 15:11:55', 0, 'BUYER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (57, 0, 'Catalog Editor', 'Catalog Editor', NULL, 'Y', 101, '2003-01-16 15:11:55', 0, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (58, 0, 'Catalog Approver', 'Catalog Approver', NULL, 'Y', 101, '2003-01-16 15:11:55', 0, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (59, 0, 'Work Supervisor', 'Work Supervisor', NULL, 'Y', 101, '2003-06-13 10:02:44', 0, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE) VALUES (60, 0, 'Support Engineer', 'Persons having Support access.', NULL, 'Y', 101, '2003-06-13 10:02:44', 0, 'SUPPLIER');
INSERT INTO ROLE (ID, ENTERPRISEID, NAME, DESCRIPTION, TYPE, ACTIVE, MODMEMBERID, MODDATE, MODVERSION, ORGANIZATIONTYPE)
VALUES (61, 0, 'Command Line User','Persons having command line access.', NULL, 'Y', 101, '20153-01-01 10:02:44', 0, 'SUPPLIER');

--COMMIT;
