-- Copyright (c) 2000-2009 TIBCO Software Inc. All Rights Reserved.

--  This work is subject  to  U.S. and  international  copyright  laws  and
--     treaties. No part  of  this  work may be  used,  practiced,  performed
--     copied, distributed, revised, modified, translated,  abridged, condensed,
--     expanded,  collected,  compiled,  linked,  recast, transformed or adapted
--     without the prior written consent of TIBCO Software Inc. any use or
--     exploitation of this work without authorization could subject the
--     perpetrator to criminal and civil liability.
--
-- Note   : Please DO NOT edit the script.

ALTER TABLE ADDRESS
ADD CONSTRAINT XPKADDRESS PRIMARY KEY (ID) ; 

ALTER TABLE ASSOCDETAIL
ADD CONSTRAINT XPKASSOCDETAIL PRIMARY KEY (ASSOCIATIONID, NAME) ;

ALTER TABLE ASSOCIATION
ADD CONSTRAINT XPKASSOCIATION PRIMARY KEY (ID) ;

ALTER TABLE ATTRIBUTEGROUP 
ADD CONSTRAINT XPKATTRIBUTEGROUP PRIMARY KEY (ID) ;

ALTER TABLE CATALOG
ADD CONSTRAINT XPKCATALOG PRIMARY KEY (ID, MODVERSION) ;

ALTER TABLE CATALOGATTRIBUTE
ADD CONSTRAINT XPKCATALOGATTR PRIMARY KEY (CATALOGID, ID, CATALOGVERSIONNUMBER) ;

ALTER TABLE CATALOGATTRIBUTEDATATYPE
ADD CONSTRAINT XPKCATATTRDATTYPE PRIMARY KEY (ID) ;

ALTER TABLE CATALOGEDITION
ADD CONSTRAINT XPKCATALOGEDIT PRIMARY KEY (ID, MODVERSION) ;

ALTER TABLE CATALOGEDITIONDETAIL
ADD CONSTRAINT XPKCATALOGEDITIONDETAIL PRIMARY KEY (NAME, CATALOGEDITIONID, CATALOGEDITIONVERSION, SEQUENCE) ; 

ALTER TABLE CATALOGEDITIONHEADER
ADD  CONSTRAINT XPKCATEDITHDR PRIMARY KEY (CATALOGEDITIONID, CATALOGEDITIONVERSIONNUMBER) ;

ALTER TABLE CATALOGEDITIONPARTY
ADD CONSTRAINT XPKCATEDITPRTY PRIMARY KEY (CATALOGEDITIONID, CATALOGEDITIONVERSIONNUMBER, PARTYORGANIZATIONID) ;

ALTER TABLE CATALOGEDITIONSTEP
ADD CONSTRAINT XPKCATEDITSTEP PRIMARY KEY (CATALOGEDITIONID, CATALOGEDITIONVERSIONNUMBER, STEPNUMBER) ; 

ALTER TABLE CATALOGFORMAT
ADD CONSTRAINT XPKCATALOGFORMAT PRIMARY KEY (ID) ;

ALTER TABLE CATALOGINPUTMAP
ADD CONSTRAINT XPKCATINPUTMAP PRIMARY KEY (ID, MODVERSION) ;

ALTER TABLE CATALOGINPUTMAPATTRIBUTE
ADD CONSTRAINT XPKCATMAPATTR PRIMARY KEY (CATALOGINPUTMAPID, CATALOGINPUTMAPVERSION,CATALOGATTRIBUTEID, SEQUENCE) ;

ALTER TABLE CATALOGINPUTMAPFRAGMENT
ADD CONSTRAINT XPKCATMAPFRAG PRIMARY KEY (CATALOGINPUTMAPID,CATALOGINPUTMAPVERSION, DATAFRAGMENTID) ;

ALTER TABLE CATALOGTYPE
ADD CONSTRAINT XPKCATALOGTYPE PRIMARY KEY (ID,MODVERSION) ;

ALTER TABLE CATALOGTYPEATTRIBUTE
ADD CONSTRAINT XPKCATATYPEATTR PRIMARY KEY (CATALOGTYPEID, CATALOGTYPEVERSION, ID, MODVERSION) ;

ALTER TABLE CLASSIFICATIONATTRIBUTE
ADD CONSTRAINT XPKCLASSATTR PRIMARY KEY (CLASSIFICATIONSCHEMEID, CSVERSIONNUMBER, HIERARCHYPOSITION) ;

ALTER TABLE CLASSIFICATIONCODE
ADD CONSTRAINT XPKCLASSCODE PRIMARY KEY (ID, CSVERSIONNUMBER) ; 

ALTER TABLE CLASSIFICATIONCODEATTRIBUTE 
ADD CONSTRAINT XPKCLASSCDEATTR PRIMARY KEY (ID, CLASSIFICATIONCODEID, CSVERSIONNUMBER) ;

ALTER TABLE CLASSIFICATIONSCHEME
ADD CONSTRAINT XPKCLASSCHEME PRIMARY KEY (ID, MODVERSION) ;

ALTER TABLE CONFIGURATIONDEFINITION
ADD CONSTRAINT XPKCONFIGDEF PRIMARY KEY (ID,MODVERSION) ;

ALTER TABLE CONVERSATION
ADD CONSTRAINT XPKCONVERSATION PRIMARY KEY (ID) ;

ALTER TABLE CONVERSATIONKEY
ADD CONSTRAINT XPKCONVERSATIONKEY PRIMARY KEY ( ID, CONVERSATIONID) ;

ALTER TABLE CURRENCY
ADD CONSTRAINT XPKCURRENCY PRIMARY KEY (ID) ;

ALTER TABLE DATAFRAGMENT
ADD CONSTRAINT XPKDATAFRAGMENT PRIMARY KEY (ID) ;

ALTER TABLE DFATTRIBUTE
ADD CONSTRAINT XPKDFATTRIBUTE PRIMARY KEY ( DATAFRAGMENTID, ID ) ;

ALTER TABLE DOMAIN
ADD CONSTRAINT XPKDOMAIN PRIMARY KEY ( TYPE ) ;

ALTER TABLE DOMAINENTRY
ADD CONSTRAINT XPKDOMAINENTRY PRIMARY KEY ( DOMAINTYPE, VALUE ) ;

ALTER TABLE DOMAINLINK
ADD CONSTRAINT XPKDOMAINLINK PRIMARY KEY ( OWNERID, DOMAINTYPE, DOMAINVALUE, SEQUENCE ) ;

ALTER TABLE DOMAINSTRING
ADD CONSTRAINT XPKDOMAINSTRING PRIMARY KEY ( DOMAINTYPE, DOMAINVALUE, LANGUAGE ) ;

ALTER TABLE DOMAINVALUE
ADD CONSTRAINT XPKDOMAINVALUE PRIMARY KEY ( DOMAINTYPE, DOMAINVALUE, SEQUENCE, OWNERID, OWNERVERSION ) ;

ALTER TABLE EMAIL
ADD CONSTRAINT XPKEMAIL PRIMARY KEY ( ID ) ;

ALTER TABLE ENTERPRISE
ADD CONSTRAINT XPKENTERPRISE PRIMARY KEY ( ID ) ;

ALTER TABLE EVENT
ADD CONSTRAINT XPKEVENT PRIMARY KEY ( ID ) ;

ALTER TABLE EVENTDETAIL
ADD CONSTRAINT XPKEVENTDETAIL PRIMARY KEY ( EVENTID, NAME, SEQUENCE ) ;

ALTER TABLE EXPORTPROFILE
ADD CONSTRAINT XPKEXPORTPROFILE PRIMARY KEY ( ID ) ;

ALTER TABLE EXPORTPROFILELINE
ADD CONSTRAINT XPKEXPORTPROFILELINE PRIMARY KEY ( LINEID ) ;

ALTER TABLE EXPORTPROFILEJOURNAL
ADD CONSTRAINT XPKEXPORTPROFILEJOURNAL PRIMARY KEY ( ID ) ;

ALTER TABLE FTP
ADD CONSTRAINT XPKFTP PRIMARY KEY ( ID ) ;

ALTER TABLE FUNC2IDMAP
ADD CONSTRAINT XPKFUNC2IDMAP PRIMARY KEY ( ID ) ;

ALTER TABLE FUNCTION
ADD CONSTRAINT XPKFUNCTION PRIMARY KEY ( ID ) ;

ALTER TABLE FUNCTIONROLE
ADD CONSTRAINT XPKFUNCTIONROLE PRIMARY KEY ( ROLEID ) ;

ALTER TABLE GENERALDOCUMENT
ADD CONSTRAINT XPKGENERALDOCUMENT PRIMARY KEY ( ID ) ;

ALTER TABLE GOLDENCOPY
ADD CONSTRAINT XPK_GOLDENCOPY PRIMARY KEY ( PRODUCTKEY, CATALOGID ) ;

ALTER TABLE HTMLELEMENTID
ADD CONSTRAINT XPKHTMLELEMENTID PRIMARY KEY ( ID ) ;

ALTER TABLE HTTP
ADD CONSTRAINT XPKHTTP PRIMARY KEY ( ID ) ;

ALTER TABLE MEMBER
ADD CONSTRAINT XPKMEMBER PRIMARY KEY ( ID ) ;

ALTER TABLE MEMBERSHIP
ADD CONSTRAINT XPKMEMBERSHIP PRIMARY KEY ( ORGANIZATIONID, MEMBERID ) ;

ALTER TABLE NAMEDVERSION
ADD CONSTRAINT XPKNAMEDVERSION PRIMARY KEY ( ID ) ;

ALTER TABLE OBJECTSEQUENCE
ADD CONSTRAINT XPKOBJECTSEQ PRIMARY KEY ( ID ) ;

ALTER TABLE ORGANIZATION
ADD CONSTRAINT CK_GLOBAL CHECK (GLOBAL IN ('Y','N'));

ALTER TABLE ORGANIZATION       
ADD CONSTRAINT XPKORGANIZATION PRIMARY KEY ( ID ) ;

ALTER TABLE PHONENUMBER
ADD CONSTRAINT XPKPHONENUMBER PRIMARY KEY ( ID ) ;

ALTER TABLE PRINCIPALKEY
ADD CONSTRAINT XPK_PRINCIPALKEY PRIMARY KEY ( CATALOGID, PRODUCTKEYID, MODVERSION ) ;

ALTER TABLE PROCESS
ADD CONSTRAINT XPKPROCESS PRIMARY KEY ( ID ) ;

ALTER TABLE PROCESSDETAIL
ADD CONSTRAINT XPKPROCESSDETAIL2 PRIMARY KEY ( PROCESSID, NAME ) ;

ALTER TABLE PROCESSLOG
ADD CONSTRAINT XPKPROCESSLOG PRIMARY KEY ( ID ) ;

ALTER TABLE PROCESSSTATE
ADD CONSTRAINT XPKPROCESSSTATE PRIMARY KEY ( ID ) ;

ALTER TABLE PROCESSSTATEHISTORY
ADD CONSTRAINT XPKPROCESSSTATEHIST PRIMARY KEY ( ID, PROCESSLOGID ) ;

ALTER TABLE PRODUCTKEY
ADD CONSTRAINT XPKPRODKEY PRIMARY KEY ( ID ) ;

ALTER TABLE PRODUCTLOG
ADD CONSTRAINT XPKPRODUCTLOG PRIMARY KEY ( PRODUCTKEYID, PROCESSLOGID, OPERATION, SUBOPERATION, OPERATIONGROUPID, PRODUCTVERSION ) ;

ALTER TABLE PRODUCTSTATUS
ADD CONSTRAINT XPKPRODUCTSTATUS PRIMARY KEY ( SOURCEPRODUCTKEYID, CHANNELORGANIZATIONID, PARTNERORGANIZATIONID, STATUSGROUP ) ;

ALTER TABLE QUEUEENTRY
ADD CONSTRAINT XPKQUEUEENTRY PRIMARY KEY ( IDVALUE, QUEUENAME ) ;

ALTER TABLE RECORDCOLLECTION
ADD CONSTRAINT XPKRECORDCOLLECTION PRIMARY KEY ( ID ) ;

ALTER TABLE RECORDCOLLECTIONDETAIL
ADD CONSTRAINT XPKRECORDCOLLECTIONID PRIMARY KEY ( RECORDCOLLECTIONID, NAME, SEQUENCE ) ;

ALTER TABLE RECORDLIST
ADD CONSTRAINT XPKRECORDLIST PRIMARY KEY ( RECORDCOLLECTIONID, PRODUCTKEYID, CATALOGID,RECORDVERSION ) ;

ALTER TABLE RELATIONSHIP
ADD CONSTRAINT XPKRELATIONSHIP PRIMARY KEY ( OWNERID, PARENTID, CHILDID, TYPE, MODDATE, CHILDOWNERID, CHILDVERSION, PARENTVERSION ) ;

ALTER TABLE RESOURCEACCESS
ADD CONSTRAINT XPKRESOURCEACCESS PRIMARY KEY ( RESOURCETYPE, RESACCESS ) ;

ALTER TABLE RESOURCEACL
ADD CONSTRAINT XPKRESOURCEACL PRIMARY KEY ( RESOURCEID, GRANTEEID, GRANTEETYPE, RESOURCETYPE, RESACCESS ) ;

ALTER TABLE ROLE
ADD CONSTRAINT XPKROLE PRIMARY KEY ( ID ) ;

ALTER TABLE ROLE2FUNCMAP
ADD CONSTRAINT XPKROLE2FUNCMAP PRIMARY KEY ( ID ) ;

ALTER TABLE ROLEACCESS
ADD CONSTRAINT XPKROLEACCESS PRIMARY KEY ( NAME, ROLEID ) ;

ALTER TABLE ROLEASSIGNMENT
ADD CONSTRAINT XPKROLEASSIGNMENT PRIMARY KEY ( ROLEID, MEMBERID ) ;

ALTER TABLE RULEDEFAULTRULES
ADD CONSTRAINT PK_RULEDEFRULES PRIMARY KEY ( ID ) ;

ALTER TABLE RULEDOUBLEDATA
ADD CONSTRAINT PK_DOUBLEDATA PRIMARY KEY ( ID ) ;

ALTER TABLE RULEINTEGERDATA
ADD CONSTRAINT PK_INTEGERDATA PRIMARY KEY ( ID ) ;

ALTER TABLE RULEMETAMODEL
ADD CONSTRAINT PK_RULEMETAMODEL PRIMARY KEY ( ID ) ;

ALTER TABLE RULEMODEL
ADD CONSTRAINT PK_RULEMODEL PRIMARY KEY ( ID ) ;

ALTER TABLE RULESTRINGDATA
ADD CONSTRAINT PK_STRINGDATA PRIMARY KEY ( ID ) ;

ALTER TABLE RULETEXTDATA
ADD CONSTRAINT PK_RULETEXTDATA PRIMARY KEY ( ID ) ;

ALTER TABLE SCREEN
ADD CONSTRAINT XPKSCREEN PRIMARY KEY ( SCREENID, LANGUAGECODE ) ;

ALTER TABLE SESSIONPRODUCTLIST
ADD CONSTRAINT XPKSESSIONPRODUCTLIST PRIMARY KEY ( SESSIONID, OWNERID, PRODUCTKEYID,RECORDVERSION ) ;

ALTER TABLE SUBCATALOG
ADD CONSTRAINT XPKSUBCATALOG PRIMARY KEY ( ID, MODVERSION ) ;

ALTER TABLE SUBCATALOGATTRIBUTE
ADD CONSTRAINT XPKSUBCATALOGATTR PRIMARY KEY ( SUBCATALOGID, POSITION, SUBCATALOGMODVERSION ) ;

ALTER TABLE SUBSETPRODUCT
ADD CONSTRAINT XPKSUBSETPRODUCT PRIMARY KEY ( ID, SUBCATALOGMODVERSION ) ;

ALTER TABLE SUBSETSEARCHCRITERION
ADD CONSTRAINT XPKSUBSETSEARCHCRITERION PRIMARY KEY ( SUBCATALOGID, SUBCATALOGVERSIONNUMBER, CATALOGATTRIBUTEID ) ;  

ALTER TABLE SUPPLIERSTATE
ADD CONSTRAINT XPKSUPPLIERSTATE PRIMARY KEY ( ID, ENTERPRISEID ) ;

ALTER TABLE SUPPLIERSTATETRANSITION
ADD CONSTRAINT XPKSUPPSTTRANS PRIMARY KEY ( FROMSTATEID, TOSTATEID, ENTERPRISEID ) ;

ALTER TABLE TRANSLATIONMAP
ADD CONSTRAINT XPKTRANSMAP PRIMARY KEY ( ID ) ;

ALTER TABLE WORKFLOWDEFINITION
ADD CONSTRAINT XPKWORKFLOWDEF PRIMARY KEY ( ID, MODVERSION ) ;

ALTER TABLE WORKFLOWFORM
ADD CONSTRAINT XPKWORKFLOWFORM PRIMARY KEY ( ID ) ;

ALTER TABLE WORKITEM
ADD CONSTRAINT XPKWORKITEM PRIMARY KEY ( ID ) ;

ALTER TABLE WORKITEMDETAIL
ADD CONSTRAINT XPKWORKITEMDETAIL PRIMARY KEY ( WORKITEMID, NAME, SEQUENCE ) ;

ALTER TABLE WORKITEMLOCK
ADD CONSTRAINT XPKWORKITEMLOCK PRIMARY KEY (PROCESSLOGID) ;

ALTER TABLE ROLEASSIGHISTORY
ADD CONSTRAINT XPKROLEASSGHIST PRIMARY KEY (ROLEID, MEMBERID, MEMBERVERSION) ;

ALTER TABLE MEMBERHISTORY
ADD CONSTRAINT XPKMEMBERHISTORY PRIMARY KEY (ID, MODVERSION) ;

ALTER TABLE MATCHRESULT 
ADD CONSTRAINT PK_MATCHRESULTID PRIMARY KEY (ID) ;

ALTER TABLE MATCHRESULTDETAILS 
ADD CONSTRAINT PK_MATCHRESULTDETAILSID PRIMARY KEY (ID) ;

ALTER TABLE MATCHCANDIDATE 
ADD CONSTRAINT PK_MATCHCANDIDATEID PRIMARY KEY (ID) ;

ALTER TABLE MATCHCANDIDATEDETAILS 
ADD CONSTRAINT PK_MATCHCANDIDATEDETAILSID PRIMARY KEY (ID) ;

ALTER TABLE MERGERESULT 
ADD CONSTRAINT PK_MERGERESULT PRIMARY KEY (ID) ;

ALTER TABLE MERGERESULTDETAIL 
ADD CONSTRAINT PK_MERGERESULTDETAIL PRIMARY KEY (ID, MERGERESULTID,NAME) ;

ALTER TABLE MERGECANDIDATE
ADD CONSTRAINT PK_MERGECANDIDATE PRIMARY KEY (ID, MERGERESULTID) ;

ALTER TABLE MERGEATTRIBUTE 
ADD CONSTRAINT PK_MERGEATTRIBUTES PRIMARY KEY (MERGERESULTID, ATTRIBUTEID,MERGERESULTDETAILSID) ;

ALTER TABLE RECORDAPPROVAL 
ADD CONSTRAINT XPKRECORDAPPROVAL PRIMARY KEY (PROCESSLOGID,RECORDKEYID, RECORDVERSION) ;

ALTER TABLE RECORDAPPROVAL
ADD CONSTRAINT CK_RECORDAPPROVAL CHECK (STATUS IN ('Pending','Approved','Rejected'));

ALTER TABLE RECORDAPPROVALHISTORY 
ADD CONSTRAINT XPKRECORDAPPROVALHISTORY PRIMARY KEY (PROCESSLOGID,RECORDKEYID, RECORDVERSION) ;

ALTER TABLE RECORDAPPROVALHISTORY 
ADD CONSTRAINT CK_RECORDAPPROVALHISTORY CHECK (STATUS IN ('PENDING','APPROVED','REJECTED'));

ALTER TABLE FUTUREDATEDRECORD 
ADD CONSTRAINT XPK_FUTUREDATEDRECORD PRIMARY KEY ( PRODUCTKEYID, CATALOGID, MODVERSION ) ; 

ALTER TABLE PERSPECTIVE ADD CONSTRAINT XPKPERSPECTIVE PRIMARY KEY (ID,MODVERSION) ; 

ALTER TABLE PERSPECTIVERELATIONSHIP ADD CONSTRAINT XPKPERSPECTIVEREL PRIMARY KEY (ID,PERSPECTIVEID,MODVERSION) ; 

ALTER TABLE PERSPECTIVEREPOATTRIBUTES ADD CONSTRAINT XPKPERSPECTIVEATT PRIMARY KEY (ID,PERSPECTIVEID,MODVERSION) ;

ALTER TABLE RECORDSYNCLOG 
ADD CONSTRAINT XPKRECSYNCLOG PRIMARY KEY (PRODUCTKEYID, PRODUCTVERSION, CHANNELORGANIZATIONID, PARTNERORGANIZATIONID, OPERATION, SUBOPERATION) ;

ALTER TABLE CLASSIFICATIONLOGICALLEVEL 
ADD CONSTRAINT XPKCSLOGICALLEVEL PRIMARY KEY (CLASSIFICATIONSCHEMEID, POSITION, CSVERSIONNUMBER) ;

ALTER TABLE CLASSIFICATIONINPUTMAP 
ADD CONSTRAINT XPKCSINPUTMAP PRIMARY KEY (ID, MODVERSION) ;

ALTER TABLE CLASSIFICATIONINPUTMAPLEVEL 
ADD CONSTRAINT XPKCSINPUTMAPLEVEL PRIMARY KEY (CLASSIFICATIONINPUTMAPID, CLASSIFICATIONINPUTMAPVERSION, LEVELPOSITION) ;

ALTER TABLE CLASSIFICATIONSCHEMEDEPLOY 
ADD CONSTRAINT XPKCSDEPLOY PRIMARY KEY (ID) ;

ALTER TABLE ATTRIBUTEHISTORY
ADD CONSTRAINT XPKATTRIBUTEHIST PRIMARY KEY (CATALOGID, ATTRIBUTEID, PRODUCTKEYID,
                                                MODVERSION, PROCESSLOGID, SEQUENCE, MODDATE) ;
ALTER TABLE METADATAXREF
ADD CONSTRAINT XPKMETADATAXREF PRIMARY KEY (CATALOGID, PRODUCTKEYID) ;

ALTER TABLE ATTRIBUTESCORE ADD CONSTRAINT XPKATTRIBUTESCORE PRIMARY KEY (ID) ;

ALTER TABLE WORKITEMATTRIBUTE
	ADD CONSTRAINT XPKWORKITEMATTRIBUTE PRIMARY KEY ( WORKITEMID, ATTRIBUTEID) ;
