apiVersion: v1
kind: ConfigMap
metadata:
  name: psc-db-env-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
data:
  {{- range $key, $val := $.Values.db.env }}
     {{ $key | indent 2  }}: {{ $val| quote }}
  {{- end }}