apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName: "{{ .Values.name }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: volume-mount-hack
          image: busybox:latest
          imagePullPolicy: Never
          command: [ "sh", "-c", "chmod -R 777 /usr/lib/postgresql/9.6/tablespaces/{velodbdata,velodbindex}" ]
          volumeMounts:
            - name: tablespaces
              mountPath: /usr/lib/postgresql/9.6/tablespaces
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.env.POSTGRES_DB }}"
          ports:
            - name: http
              containerPort: {{ .Values.postgresql.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tablespaces
              mountPath: /usr/lib/postgresql/9.6/tablespaces
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            - name: mdm-db-install-scripts
              mountPath: /dbscripts/mdm/install
            - name: mdm-db-configure-scripts
              mountPath: /dbscripts/mdm/configure
            - name: mdm-db-install-ddl-scripts
              mountPath: /dbscripts/mdm/install/ddl
            - name: mdm-db-install-seed-scripts
              mountPath: /dbscripts/mdm/install/seed
            - name: mdm-db-install-triggers-scripts
              mountPath: /dbscripts/mdm/install/triggers
            - name: fc-db-install-scripts
              mountPath: /dbscripts/fc/install
            - name: fc-db-install-seed-scripts
              mountPath: /dbscripts/fc/install/seed
      volumes:
        - name: tablespaces
          emptyDir: {}
        - name: custom-init-scripts
          configMap:
            name: {{ template "postgresql.initdbScriptsCM" . }}
            defaultMode: 0777
        - name: mdm-db-install-scripts
          configMap:
            name: mdm-db-install-scripts
            defaultMode: 0777
        - name: mdm-db-configure-scripts
          configMap:
            name: mdm-db-configure-scripts
            defaultMode: 0777
        - name: mdm-db-install-ddl-scripts
          configMap:
            name: mdm-db-install-ddl-scripts
            defaultMode: 0777
        - name: mdm-db-install-seed-scripts
          configMap:
            name: mdm-db-install-seed-scripts
            defaultMode: 0777
        - name: mdm-db-install-triggers-scripts
          configMap:
            name: mdm-db-install-triggers-scripts
            defaultMode: 0777
        - name: fc-db-install-scripts
          configMap:
            name: fc-db-install-scripts
            defaultMode: 0777
        - name: fc-db-install-seed-scripts
          configMap:
            name: fc-db-install-scripts
            defaultMode: 0777