apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName: "{{ .Values.name }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: git-cloner
          image: alpine/git
          imagePullPolicy: Never
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/alpanachaphalkar/TIBCO-PSC-DB.git
            - /repo
          volumeMounts:
            - mountPath: /repo
              name: repo
{{/*        - name: curl-unziper*/}}
{{/*          image: alpine/curl*/}}
{{/*          imagePullPolicy: Never*/}}
{{/*          command: [ "sh", "-c", "cd /psc-data-init/ && ./init.sh" ]*/}}
{{/*          envFrom:*/}}
{{/*            - secretRef:*/}}
{{/*                name: {{ .Release.Name }}-secret*/}}
{{/*          env:*/}}
{{/*            - name: JFROG_PSC_JAVA_HOME_URL*/}}
{{/*              value: "https://skydeportal.jfrog.io/artifactory/fo-fulfillment-generic/Sky%20Deutschland/psc-500-hf2/psc-data/java-home.zip"*/}}
{{/*            - name: JFROG_PSC_MQ_HOME_URL*/}}
{{/*              value: "https://skydeportal.jfrog.io/artifactory/fo-fulfillment-generic/Sky%20Deutschland/psc-500-hf2/psc-data/mq-home.zip"*/}}
{{/*            - name: MQ_HOME*/}}
{{/*              value: {{ .Values.db.env.MQ_HOME }}*/}}
{{/*            - name: JAVA_HOME*/}}
{{/*              value: {{ .Values.db.env.JAVA_HOME }}*/}}
{{/*          volumeMounts:*/}}
{{/*            - mountPath: /psc-data*/}}
{{/*              name: psc-data*/}}
{{/*            - mountPath: /psc-data-init/*/}}
{{/*              name: psc-data-init-script*/}}
        - name: volume-mount-hack
          image: busybox:latest
          imagePullPolicy: Never
          command: [ "sh", "-c", "chmod -R 777 /usr/lib/postgresql/12/tablespaces  /repo /psc-data" ]
          volumeMounts:
            - name: tablespaces
              mountPath: /usr/lib/postgresql/12/tablespaces
            - name: repo
              mountPath: /repo
            - name: psc-data
              mountPath: /psc-data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.env.POSTGRES_DB }}"
          envFrom:
            - configMapRef:
                name: psc-db-env-config
          ports:
            - name: http
              containerPort: {{ .Values.postgresql.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tablespaces
              mountPath: /usr/lib/postgresql/12/tablespaces
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            - name: repo
              mountPath: /repo
            - name: psc-data
              mountPath: /psc-data
      volumes:
        - name: tablespaces
          persistentVolumeClaim:
            claimName: db-tablespace-pvc
        - name: repo
          emptyDir: {}
        - name: psc-data
          emptyDir: {}
        - name: custom-init-scripts
          configMap:
            name: {{ template "postgresql.initdbScriptsCM" . }}
            defaultMode: 0777
{{/*        - name: psc-data-init-script*/}}
{{/*          configMap:*/}}
{{/*            name: psc-data-init-script*/}}
{{/*            defaultMode: 0777*/}}