BEGIN TRANSACTION;

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('DOCSUBTYPE', 'ACBulkModelDocSub', 'Bulk Model Publish');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('APPFUNCTION', 'ACBulkModelDocSub', 'Bulk Model Publish');

INSERT INTO DOMAINENTRY ( DOMAINTYPE, VALUE, DESCRIPTION ) VALUES ('APPFUNCTION', 'BULKMODELPUBLISH', 'Bulk Model Publish');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('DOCSUBTYPE', 'EnterpriseDataExportDocSub', 'Enterprise Data Export');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('APPFUNCTION', 'EnterpriseDataExportDocSub', 'Enterprise Data Export');

INSERT INTO DOMAINENTRY ( DOMAINTYPE, VALUE, DESCRIPTION ) VALUES ('APPFUNCTION', 'ENTERPRISEDATAEXPORT', 'Enterprise Data Export');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('DOCSUBTYPE', 'EnterpriseDataImportDocSub', 'Enterprise Full Data Import');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('APPFUNCTION', 'EnterpriseDataImportDocSub', 'Enterprise Full Data Import');

INSERT INTO DOMAINENTRY ( DOMAINTYPE, VALUE, DESCRIPTION ) VALUES ('APPFUNCTION', 'ENTERPRISEDATAIMPORT', 'Enterprise Full Data Import');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('DOCSUBTYPE', 'EnterpriseDataPartialImportDocSub', 'Enterprise Partial Data Import');

INSERT INTO DOMAINENTRY(DOMAINTYPE, VALUE, DESCRIPTION) VALUES ('APPFUNCTION', 'EnterpriseDataPartialImportDocSub', 'Enterprise Partial Data Import');

INSERT INTO DOMAINENTRY ( DOMAINTYPE, VALUE, DESCRIPTION ) VALUES ('APPFUNCTION', 'ENTERPRISEPARTIALDATAIMPORT', 'Enterprise Partial Data Import');
COMMIT;